// Code generated by protoc-gen-go. DO NOT EDIT.
// source: full.proto

package full

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComplexMessage_SimpleEnum int32

const (
	ComplexMessage_UNSPECIFIED ComplexMessage_SimpleEnum = 0
	ComplexMessage_VALUE_A     ComplexMessage_SimpleEnum = 1
	ComplexMessage_VALUE_B     ComplexMessage_SimpleEnum = 2
	ComplexMessage_VALUE_B1    ComplexMessage_SimpleEnum = 3
	ComplexMessage_VALUE_B2    ComplexMessage_SimpleEnum = 4
	ComplexMessage_VALUE_B3    ComplexMessage_SimpleEnum = 5
	ComplexMessage_VALUE_B4    ComplexMessage_SimpleEnum = 6
	ComplexMessage_VALUE_B5    ComplexMessage_SimpleEnum = 7
	ComplexMessage_VALUE_B6    ComplexMessage_SimpleEnum = 8
	ComplexMessage_VALUE_B7    ComplexMessage_SimpleEnum = 9
	ComplexMessage_VALUE_B8    ComplexMessage_SimpleEnum = 1000
)

var ComplexMessage_SimpleEnum_name = map[int32]string{
	0:    "UNSPECIFIED",
	1:    "VALUE_A",
	2:    "VALUE_B",
	3:    "VALUE_B1",
	4:    "VALUE_B2",
	5:    "VALUE_B3",
	6:    "VALUE_B4",
	7:    "VALUE_B5",
	8:    "VALUE_B6",
	9:    "VALUE_B7",
	1000: "VALUE_B8",
}
var ComplexMessage_SimpleEnum_value = map[string]int32{
	"UNSPECIFIED": 0,
	"VALUE_A":     1,
	"VALUE_B":     2,
	"VALUE_B1":    3,
	"VALUE_B2":    4,
	"VALUE_B3":    5,
	"VALUE_B4":    6,
	"VALUE_B5":    7,
	"VALUE_B6":    8,
	"VALUE_B7":    9,
	"VALUE_B8":    1000,
}

func (x ComplexMessage_SimpleEnum) String() string {
	return proto.EnumName(ComplexMessage_SimpleEnum_name, int32(x))
}
func (ComplexMessage_SimpleEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_full_d33c4bcc9f55aede, []int{0, 0}
}

type ComplexMessage struct {
	Enum           ComplexMessage_SimpleEnum     `protobuf:"varint,1,opt,name=enum,proto3,enum=ComplexMessage_SimpleEnum" json:"enum,omitempty"`
	ScalarInt32    int32                         `protobuf:"varint,2,opt,name=scalar_int32,json=scalarInt32,proto3" json:"scalar_int32,omitempty"`
	ScalarInt64    int64                         `protobuf:"varint,3,opt,name=scalar_int64,json=scalarInt64,proto3" json:"scalar_int64,omitempty"`
	ScalarUint32   uint32                        `protobuf:"varint,4,opt,name=scalar_uint32,json=scalarUint32,proto3" json:"scalar_uint32,omitempty"`
	ScalarUint64   uint64                        `protobuf:"varint,5,opt,name=scalar_uint64,json=scalarUint64,proto3" json:"scalar_uint64,omitempty"`
	ScalarSint32   int32                         `protobuf:"zigzag32,6,opt,name=scalar_sint32,json=scalarSint32,proto3" json:"scalar_sint32,omitempty"`
	ScalarSint64   int64                         `protobuf:"zigzag64,7,opt,name=scalar_sint64,json=scalarSint64,proto3" json:"scalar_sint64,omitempty"`
	ScalarFixed32  uint32                        `protobuf:"fixed32,8,opt,name=scalar_fixed32,json=scalarFixed32,proto3" json:"scalar_fixed32,omitempty"`
	ScalarFixed64  uint64                        `protobuf:"fixed64,9,opt,name=scalar_fixed64,json=scalarFixed64,proto3" json:"scalar_fixed64,omitempty"`
	ScalarSfixed32 int32                         `protobuf:"fixed32,10,opt,name=scalar_sfixed32,json=scalarSfixed32,proto3" json:"scalar_sfixed32,omitempty"`
	ScalarSfixed64 int64                         `protobuf:"fixed64,11,opt,name=scalar_sfixed64,json=scalarSfixed64,proto3" json:"scalar_sfixed64,omitempty"`
	ScalarDouble   float64                       `protobuf:"fixed64,12,opt,name=scalar_double,json=scalarDouble,proto3" json:"scalar_double,omitempty"`
	ScalarFloat    float32                       `protobuf:"fixed32,13,opt,name=scalar_float,json=scalarFloat,proto3" json:"scalar_float,omitempty"`
	ScalarBool     bool                          `protobuf:"varint,14,opt,name=scalar_bool,json=scalarBool,proto3" json:"scalar_bool,omitempty"`
	ScalarString   string                        `protobuf:"bytes,15,opt,name=scalar_string,json=scalarString,proto3" json:"scalar_string,omitempty"`
	Message        *ComplexMessage_SimpleMessage `protobuf:"bytes,16,opt,name=message,proto3" json:"message,omitempty"`
	Bytes          []byte                        `protobuf:"bytes,17,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Maps
	MapEnum   map[int32]ComplexMessage_SimpleEnum      `protobuf:"bytes,18,rep,name=map_enum,json=mapEnum,proto3" json:"map_enum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=ComplexMessage_SimpleEnum"`
	MapScalar map[int32]int32                          `protobuf:"bytes,19,rep,name=map_scalar,json=mapScalar,proto3" json:"map_scalar,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	MapMsg    map[string]*ComplexMessage_SimpleMessage `protobuf:"bytes,20,rep,name=map_msg,json=mapMsg,proto3" json:"map_msg,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapBytes  map[string][]byte                        `protobuf:"bytes,21,rep,name=map_bytes,json=mapBytes,proto3" json:"map_bytes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MapString map[string]string                        `protobuf:"bytes,22,rep,name=map_string,json=mapString,proto3" json:"map_string,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Repeated
	REnum   []ComplexMessage_SimpleEnum     `protobuf:"varint,23,rep,packed,name=r_enum,json=rEnum,proto3,enum=ComplexMessage_SimpleEnum" json:"r_enum,omitempty"`
	RScalar []int32                         `protobuf:"varint,24,rep,packed,name=r_scalar,json=rScalar,proto3" json:"r_scalar,omitempty"`
	RMsg    []*ComplexMessage_SimpleMessage `protobuf:"bytes,25,rep,name=r_msg,json=rMsg,proto3" json:"r_msg,omitempty"`
	RBytes  [][]byte                        `protobuf:"bytes,26,rep,name=r_bytes,json=rBytes,proto3" json:"r_bytes,omitempty"`
	// Types that are valid to be assigned to Oneof:
	//	*ComplexMessage_OneofScalar
	//	*ComplexMessage_OneofMessage
	//	*ComplexMessage_OneofEnum
	Oneof                isComplexMessage_Oneof `protobuf_oneof:"oneof"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ComplexMessage) Reset()         { *m = ComplexMessage{} }
func (m *ComplexMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage) ProtoMessage()    {}
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_full_d33c4bcc9f55aede, []int{0}
}
func (m *ComplexMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage.Unmarshal(m, b)
}
func (m *ComplexMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage.Marshal(b, m, deterministic)
}
func (dst *ComplexMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage.Merge(dst, src)
}
func (m *ComplexMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage.Size(m)
}
func (m *ComplexMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage proto.InternalMessageInfo

func (m *ComplexMessage) GetEnum() ComplexMessage_SimpleEnum {
	if m != nil {
		return m.Enum
	}
	return ComplexMessage_UNSPECIFIED
}

func (m *ComplexMessage) GetScalarInt32() int32 {
	if m != nil {
		return m.ScalarInt32
	}
	return 0
}

func (m *ComplexMessage) GetScalarInt64() int64 {
	if m != nil {
		return m.ScalarInt64
	}
	return 0
}

func (m *ComplexMessage) GetScalarUint32() uint32 {
	if m != nil {
		return m.ScalarUint32
	}
	return 0
}

func (m *ComplexMessage) GetScalarUint64() uint64 {
	if m != nil {
		return m.ScalarUint64
	}
	return 0
}

func (m *ComplexMessage) GetScalarSint32() int32 {
	if m != nil {
		return m.ScalarSint32
	}
	return 0
}

func (m *ComplexMessage) GetScalarSint64() int64 {
	if m != nil {
		return m.ScalarSint64
	}
	return 0
}

func (m *ComplexMessage) GetScalarFixed32() uint32 {
	if m != nil {
		return m.ScalarFixed32
	}
	return 0
}

func (m *ComplexMessage) GetScalarFixed64() uint64 {
	if m != nil {
		return m.ScalarFixed64
	}
	return 0
}

func (m *ComplexMessage) GetScalarSfixed32() int32 {
	if m != nil {
		return m.ScalarSfixed32
	}
	return 0
}

func (m *ComplexMessage) GetScalarSfixed64() int64 {
	if m != nil {
		return m.ScalarSfixed64
	}
	return 0
}

func (m *ComplexMessage) GetScalarDouble() float64 {
	if m != nil {
		return m.ScalarDouble
	}
	return 0
}

func (m *ComplexMessage) GetScalarFloat() float32 {
	if m != nil {
		return m.ScalarFloat
	}
	return 0
}

func (m *ComplexMessage) GetScalarBool() bool {
	if m != nil {
		return m.ScalarBool
	}
	return false
}

func (m *ComplexMessage) GetScalarString() string {
	if m != nil {
		return m.ScalarString
	}
	return ""
}

func (m *ComplexMessage) GetMessage() *ComplexMessage_SimpleMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ComplexMessage) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *ComplexMessage) GetMapEnum() map[int32]ComplexMessage_SimpleEnum {
	if m != nil {
		return m.MapEnum
	}
	return nil
}

func (m *ComplexMessage) GetMapScalar() map[int32]int32 {
	if m != nil {
		return m.MapScalar
	}
	return nil
}

func (m *ComplexMessage) GetMapMsg() map[string]*ComplexMessage_SimpleMessage {
	if m != nil {
		return m.MapMsg
	}
	return nil
}

func (m *ComplexMessage) GetMapBytes() map[string][]byte {
	if m != nil {
		return m.MapBytes
	}
	return nil
}

func (m *ComplexMessage) GetMapString() map[string]string {
	if m != nil {
		return m.MapString
	}
	return nil
}

func (m *ComplexMessage) GetREnum() []ComplexMessage_SimpleEnum {
	if m != nil {
		return m.REnum
	}
	return nil
}

func (m *ComplexMessage) GetRScalar() []int32 {
	if m != nil {
		return m.RScalar
	}
	return nil
}

func (m *ComplexMessage) GetRMsg() []*ComplexMessage_SimpleMessage {
	if m != nil {
		return m.RMsg
	}
	return nil
}

func (m *ComplexMessage) GetRBytes() [][]byte {
	if m != nil {
		return m.RBytes
	}
	return nil
}

type isComplexMessage_Oneof interface {
	isComplexMessage_Oneof()
}

type ComplexMessage_OneofScalar struct {
	OneofScalar int32 `protobuf:"varint,27,opt,name=oneof_scalar,json=oneofScalar,proto3,oneof"`
}

type ComplexMessage_OneofMessage struct {
	OneofMessage *ComplexMessage_SimpleMessage `protobuf:"bytes,28,opt,name=oneof_message,json=oneofMessage,proto3,oneof"`
}

type ComplexMessage_OneofEnum struct {
	OneofEnum ComplexMessage_SimpleEnum `protobuf:"varint,29,opt,name=oneof_enum,json=oneofEnum,proto3,enum=ComplexMessage_SimpleEnum,oneof"`
}

func (*ComplexMessage_OneofScalar) isComplexMessage_Oneof() {}

func (*ComplexMessage_OneofMessage) isComplexMessage_Oneof() {}

func (*ComplexMessage_OneofEnum) isComplexMessage_Oneof() {}

func (m *ComplexMessage) GetOneof() isComplexMessage_Oneof {
	if m != nil {
		return m.Oneof
	}
	return nil
}

func (m *ComplexMessage) GetOneofScalar() int32 {
	if x, ok := m.GetOneof().(*ComplexMessage_OneofScalar); ok {
		return x.OneofScalar
	}
	return 0
}

func (m *ComplexMessage) GetOneofMessage() *ComplexMessage_SimpleMessage {
	if x, ok := m.GetOneof().(*ComplexMessage_OneofMessage); ok {
		return x.OneofMessage
	}
	return nil
}

func (m *ComplexMessage) GetOneofEnum() ComplexMessage_SimpleEnum {
	if x, ok := m.GetOneof().(*ComplexMessage_OneofEnum); ok {
		return x.OneofEnum
	}
	return ComplexMessage_UNSPECIFIED
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ComplexMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ComplexMessage_OneofMarshaler, _ComplexMessage_OneofUnmarshaler, _ComplexMessage_OneofSizer, []interface{}{
		(*ComplexMessage_OneofScalar)(nil),
		(*ComplexMessage_OneofMessage)(nil),
		(*ComplexMessage_OneofEnum)(nil),
	}
}

func _ComplexMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ComplexMessage)
	// oneof
	switch x := m.Oneof.(type) {
	case *ComplexMessage_OneofScalar:
		b.EncodeVarint(27<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.OneofScalar))
	case *ComplexMessage_OneofMessage:
		b.EncodeVarint(28<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OneofMessage); err != nil {
			return err
		}
	case *ComplexMessage_OneofEnum:
		b.EncodeVarint(29<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.OneofEnum))
	case nil:
	default:
		return fmt.Errorf("ComplexMessage.Oneof has unexpected type %T", x)
	}
	return nil
}

func _ComplexMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ComplexMessage)
	switch tag {
	case 27: // oneof.oneof_scalar
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Oneof = &ComplexMessage_OneofScalar{int32(x)}
		return true, err
	case 28: // oneof.oneof_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ComplexMessage_SimpleMessage)
		err := b.DecodeMessage(msg)
		m.Oneof = &ComplexMessage_OneofMessage{msg}
		return true, err
	case 29: // oneof.oneof_enum
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Oneof = &ComplexMessage_OneofEnum{ComplexMessage_SimpleEnum(x)}
		return true, err
	default:
		return false, nil
	}
}

func _ComplexMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ComplexMessage)
	// oneof
	switch x := m.Oneof.(type) {
	case *ComplexMessage_OneofScalar:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(x.OneofScalar))
	case *ComplexMessage_OneofMessage:
		s := proto.Size(x.OneofMessage)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ComplexMessage_OneofEnum:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(x.OneofEnum))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ComplexMessage_SimpleMessage struct {
	SomeField            int32    `protobuf:"varint,1,opt,name=some_field,json=someField,proto3" json:"some_field,omitempty"`
	SomeField2           string   `protobuf:"bytes,2,opt,name=some_field2,json=someField2,proto3" json:"some_field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplexMessage_SimpleMessage) Reset()         { *m = ComplexMessage_SimpleMessage{} }
func (m *ComplexMessage_SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage_SimpleMessage) ProtoMessage()    {}
func (*ComplexMessage_SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_full_d33c4bcc9f55aede, []int{0, 0}
}
func (m *ComplexMessage_SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Unmarshal(m, b)
}
func (m *ComplexMessage_SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Marshal(b, m, deterministic)
}
func (dst *ComplexMessage_SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage_SimpleMessage.Merge(dst, src)
}
func (m *ComplexMessage_SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Size(m)
}
func (m *ComplexMessage_SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage_SimpleMessage proto.InternalMessageInfo

func (m *ComplexMessage_SimpleMessage) GetSomeField() int32 {
	if m != nil {
		return m.SomeField
	}
	return 0
}

func (m *ComplexMessage_SimpleMessage) GetSomeField2() string {
	if m != nil {
		return m.SomeField2
	}
	return ""
}

func init() {
	proto.RegisterType((*ComplexMessage)(nil), "ComplexMessage")
	proto.RegisterMapType((map[string][]byte)(nil), "ComplexMessage.MapBytesEntry")
	proto.RegisterMapType((map[int32]ComplexMessage_SimpleEnum)(nil), "ComplexMessage.MapEnumEntry")
	proto.RegisterMapType((map[string]*ComplexMessage_SimpleMessage)(nil), "ComplexMessage.MapMsgEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "ComplexMessage.MapScalarEntry")
	proto.RegisterMapType((map[string]string)(nil), "ComplexMessage.MapStringEntry")
	proto.RegisterType((*ComplexMessage_SimpleMessage)(nil), "ComplexMessage.SimpleMessage")
	proto.RegisterEnum("ComplexMessage_SimpleEnum", ComplexMessage_SimpleEnum_name, ComplexMessage_SimpleEnum_value)
}

func init() { proto.RegisterFile("full.proto", fileDescriptor_full_d33c4bcc9f55aede) }

var fileDescriptor_full_d33c4bcc9f55aede = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xd1, 0x8e, 0xe2, 0x36,
	0x14, 0xc5, 0x84, 0x10, 0x72, 0x13, 0x20, 0xeb, 0x4e, 0xbb, 0x5e, 0x76, 0x69, 0xdd, 0x5d, 0x55,
	0xf5, 0x13, 0xea, 0x86, 0x34, 0xb3, 0xda, 0x6d, 0x1f, 0x96, 0x19, 0xd0, 0x8c, 0xd4, 0x69, 0x2b,
	0xa3, 0x19, 0xf5, 0x0d, 0x41, 0x27, 0x20, 0xd4, 0x84, 0xa0, 0x04, 0xaa, 0x99, 0x3f, 0xea, 0xa7,
	0xf5, 0xbd, 0x3f, 0x50, 0xc5, 0x4e, 0x18, 0x87, 0xa6, 0x62, 0xdf, 0x38, 0xd7, 0xe7, 0x1c, 0xfb,
	0x5e, 0x9f, 0x18, 0x80, 0xe5, 0x3e, 0x0c, 0x07, 0xdb, 0x24, 0xde, 0xc5, 0xaf, 0xff, 0xe9, 0x40,
	0xe7, 0x22, 0x8e, 0xb6, 0x61, 0xf0, 0x70, 0x13, 0xa4, 0xe9, 0x7c, 0x15, 0xe0, 0x01, 0x34, 0x82,
	0xcd, 0x3e, 0x22, 0x88, 0x22, 0xd6, 0x71, 0x7b, 0x83, 0xf2, 0xf2, 0x60, 0xba, 0xce, 0xe0, 0x78,
	0xb3, 0x8f, 0xb8, 0xe0, 0xe1, 0xaf, 0xc1, 0x4e, 0x7f, 0x9f, 0x87, 0xf3, 0x64, 0xb6, 0xde, 0xec,
	0x86, 0x2e, 0xa9, 0x53, 0xc4, 0x74, 0x6e, 0xc9, 0xda, 0x75, 0x56, 0x2a, 0x53, 0x7c, 0x8f, 0x68,
	0x14, 0x31, 0x4d, 0xa1, 0xf8, 0x1e, 0x7e, 0x03, 0xed, 0x9c, 0xb2, 0x97, 0x36, 0x0d, 0x8a, 0x58,
	0x9b, 0xe7, 0xba, 0x5b, 0x51, 0x3b, 0x22, 0xf9, 0x1e, 0xd1, 0x29, 0x62, 0x0d, 0x95, 0x54, 0x72,
	0x4a, 0xa5, 0x53, 0x93, 0x22, 0xf6, 0xac, 0x20, 0x4d, 0x8f, 0x9d, 0x52, 0xe9, 0x64, 0x50, 0xc4,
	0xb0, 0x4a, 0xf2, 0x3d, 0xfc, 0x0d, 0x74, 0x72, 0xd2, 0x72, 0xfd, 0x10, 0xdc, 0x0f, 0x5d, 0xd2,
	0xa2, 0x88, 0x19, 0x3c, 0x97, 0x4e, 0x64, 0xf1, 0x98, 0xe6, 0x7b, 0xc4, 0xa4, 0x88, 0x35, 0x4b,
	0x34, 0xdf, 0xc3, 0xdf, 0x42, 0xb7, 0xd8, 0xb2, 0xb0, 0x03, 0x8a, 0x58, 0x97, 0xe7, 0xea, 0x69,
	0x5e, 0xfd, 0x0f, 0xd1, 0xf7, 0x88, 0x45, 0x11, 0x73, 0xca, 0xc4, 0x52, 0xa7, 0xf7, 0xf1, 0x7e,
	0x11, 0x06, 0xc4, 0xa6, 0x88, 0xa1, 0xa2, 0x89, 0x4b, 0x51, 0x53, 0x66, 0xbf, 0x0c, 0xe3, 0xf9,
	0x8e, 0xb4, 0x29, 0x62, 0xf5, 0x62, 0xf6, 0x93, 0xac, 0x84, 0xbf, 0x82, 0x1c, 0xce, 0x16, 0x71,
	0x1c, 0x92, 0x0e, 0x45, 0xac, 0xc5, 0x41, 0x96, 0x46, 0x71, 0x1c, 0xaa, 0xd3, 0xda, 0x25, 0xeb,
	0xcd, 0x8a, 0x74, 0x29, 0x62, 0xe6, 0x61, 0x5a, 0xa2, 0x86, 0xcf, 0xc1, 0x88, 0x64, 0x46, 0x88,
	0x43, 0x11, 0xb3, 0xdc, 0x7e, 0x75, 0x74, 0x72, 0xc4, 0x0b, 0x36, 0x3e, 0x03, 0x7d, 0xf1, 0xb8,
	0x0b, 0x52, 0xf2, 0x8c, 0x22, 0x66, 0x73, 0x09, 0xf0, 0x39, 0xb4, 0xa2, 0xf9, 0x76, 0x26, 0xa2,
	0x88, 0xa9, 0xc6, 0x2c, 0xf7, 0xd5, 0xb1, 0xdf, 0xcd, 0x7c, 0x9b, 0xe5, 0x70, 0xbc, 0xd9, 0x25,
	0x8f, 0xdc, 0x88, 0x24, 0xc2, 0x3f, 0x02, 0x64, 0x42, 0x79, 0x36, 0xf2, 0x99, 0x90, 0x7e, 0x59,
	0x21, 0x9d, 0x0a, 0x82, 0x14, 0x9b, 0x51, 0x81, 0xb1, 0x07, 0x99, 0xd3, 0x2c, 0x4a, 0x57, 0xe4,
	0x4c, 0x68, 0x5f, 0x56, 0x68, 0x6f, 0xd2, 0x95, 0x14, 0x36, 0x23, 0x01, 0xf0, 0x7b, 0xc8, 0x2c,
	0x66, 0xb2, 0x8f, 0xcf, 0x85, 0xae, 0x5f, 0xa1, 0x1b, 0x65, 0xeb, 0x52, 0x99, 0x75, 0x27, 0xe0,
	0xe1, 0xc0, 0x72, 0xb4, 0x5f, 0xfc, 0xff, 0x81, 0x05, 0x41, 0x39, 0xb0, 0x9c, 0xfb, 0x5b, 0x68,
	0x26, 0x72, 0x4c, 0xcf, 0xa9, 0x76, 0xe2, 0x8b, 0xd5, 0x13, 0x31, 0xa2, 0x17, 0xd0, 0x4a, 0x8a,
	0x01, 0x11, 0xaa, 0x31, 0x9d, 0x1b, 0x49, 0xde, 0xbe, 0x0b, 0x7a, 0x22, 0x9a, 0x7f, 0x51, 0xdd,
	0x44, 0xf9, 0x0e, 0x1b, 0x49, 0xd6, 0xfc, 0x73, 0x30, 0x92, 0xbc, 0xf5, 0x1e, 0xd5, 0x98, 0xcd,
	0x9b, 0x89, 0xec, 0xec, 0x0d, 0xd8, 0xf1, 0x26, 0x88, 0x97, 0xc5, 0x5e, 0x2f, 0xb3, 0xa7, 0xe1,
	0xaa, 0xc6, 0x2d, 0x51, 0xcd, 0x77, 0xbc, 0x84, 0xb6, 0x24, 0x15, 0xe9, 0x79, 0xf5, 0x09, 0xe9,
	0xb9, 0xaa, 0x71, 0x69, 0x5d, 0xbc, 0x5a, 0x1f, 0x00, 0xa4, 0x8b, 0x98, 0x44, 0xff, 0xd4, 0xdb,
	0x75, 0x55, 0xe3, 0xa6, 0xe0, 0x67, 0xa0, 0xf7, 0x0b, 0xb4, 0x4b, 0xee, 0xb8, 0x0f, 0x90, 0xc6,
	0x51, 0x30, 0x5b, 0xae, 0x83, 0xf0, 0x5e, 0xbc, 0x84, 0x3a, 0x37, 0xb3, 0xca, 0x24, 0x2b, 0x88,
	0x0f, 0xe6, 0xb0, 0x2c, 0x5f, 0x3c, 0x93, 0xc3, 0x61, 0xdd, 0xed, 0xdd, 0x81, 0xad, 0x86, 0x13,
	0x3b, 0xa0, 0xfd, 0x11, 0x3c, 0xe6, 0x46, 0xd9, 0x4f, 0xfc, 0x1d, 0xe8, 0x7f, 0xce, 0xc3, 0x7d,
	0x20, 0xc4, 0x27, 0x2e, 0x4d, 0x10, 0xdf, 0xd7, 0xdf, 0xa1, 0xde, 0x0f, 0xd0, 0x29, 0x27, 0xb7,
	0xc2, 0xf9, 0x4c, 0x75, 0xd6, 0x55, 0xf5, 0x6f, 0x60, 0x29, 0xd9, 0x55, 0xa5, 0xa6, 0x94, 0x0e,
	0x55, 0xe9, 0xc9, 0xcb, 0x57, 0x9c, 0x3f, 0x40, 0xbb, 0x94, 0xee, 0x0a, 0xef, 0xd2, 0xb1, 0xec,
	0x8a, 0xa6, 0x9e, 0xd2, 0x7d, 0x4a, 0x6d, 0x2a, 0xea, 0xd7, 0x7f, 0x21, 0x80, 0xa7, 0x61, 0xe1,
	0x2e, 0x58, 0xb7, 0x3f, 0x4f, 0x7f, 0x1d, 0x5f, 0x5c, 0x4f, 0xae, 0xc7, 0x97, 0x4e, 0x0d, 0x5b,
	0x60, 0xdc, 0x7d, 0xfc, 0xe9, 0x76, 0x3c, 0xfb, 0xe8, 0xa0, 0x27, 0x30, 0x72, 0xea, 0xd8, 0x86,
	0x56, 0x0e, 0xde, 0x3a, 0x9a, 0x82, 0x5c, 0xa7, 0xa1, 0xa0, 0xa1, 0xa3, 0x2b, 0xc8, 0x73, 0x9a,
	0x0a, 0xfa, 0xde, 0x31, 0x14, 0xe4, 0x3b, 0x2d, 0x05, 0x9d, 0x3b, 0x26, 0x6e, 0x1f, 0xd0, 0x3b,
	0xe7, 0x6f, 0x63, 0x64, 0x80, 0x2e, 0x32, 0xb7, 0x68, 0x8a, 0x3f, 0xdf, 0xe1, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x60, 0xc2, 0xd9, 0x66, 0x8a, 0x07, 0x00, 0x00,
}
