// Code generated by protoc-gen-go. DO NOT EDIT.
// source: full.proto

package full

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ComplexMessage_SimpleEnum int32

const (
	ComplexMessage_UNSPECIFIED ComplexMessage_SimpleEnum = 0
	ComplexMessage_VALUE_A     ComplexMessage_SimpleEnum = 1
	ComplexMessage_VALUE_B     ComplexMessage_SimpleEnum = 2
	ComplexMessage_VALUE_B1    ComplexMessage_SimpleEnum = 3
	ComplexMessage_VALUE_B2    ComplexMessage_SimpleEnum = 4
	ComplexMessage_VALUE_B3    ComplexMessage_SimpleEnum = 5
	ComplexMessage_VALUE_B4    ComplexMessage_SimpleEnum = 6
	ComplexMessage_VALUE_B5    ComplexMessage_SimpleEnum = 7
	ComplexMessage_VALUE_B6    ComplexMessage_SimpleEnum = 8
	ComplexMessage_VALUE_B7    ComplexMessage_SimpleEnum = 9
	ComplexMessage_VALUE_B8    ComplexMessage_SimpleEnum = 1000
)

var ComplexMessage_SimpleEnum_name = map[int32]string{
	0:    "UNSPECIFIED",
	1:    "VALUE_A",
	2:    "VALUE_B",
	3:    "VALUE_B1",
	4:    "VALUE_B2",
	5:    "VALUE_B3",
	6:    "VALUE_B4",
	7:    "VALUE_B5",
	8:    "VALUE_B6",
	9:    "VALUE_B7",
	1000: "VALUE_B8",
}
var ComplexMessage_SimpleEnum_value = map[string]int32{
	"UNSPECIFIED": 0,
	"VALUE_A":     1,
	"VALUE_B":     2,
	"VALUE_B1":    3,
	"VALUE_B2":    4,
	"VALUE_B3":    5,
	"VALUE_B4":    6,
	"VALUE_B5":    7,
	"VALUE_B6":    8,
	"VALUE_B7":    9,
	"VALUE_B8":    1000,
}

func (x ComplexMessage_SimpleEnum) String() string {
	return proto.EnumName(ComplexMessage_SimpleEnum_name, int32(x))
}
func (ComplexMessage_SimpleEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_full_275f2977295e095e, []int{0, 0}
}

type ComplexMessage struct {
	Enum    ComplexMessage_SimpleEnum     `protobuf:"varint,1,opt,name=enum,proto3,enum=ComplexMessage_SimpleEnum" json:"enum,omitempty"`
	Scalar  int32                         `protobuf:"varint,2,opt,name=scalar,proto3" json:"scalar,omitempty"`
	Message *ComplexMessage_SimpleMessage `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Bytes   []byte                        `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// Maps
	MapEnum   map[int32]ComplexMessage_SimpleEnum     `protobuf:"bytes,5,rep,name=map_enum,json=mapEnum,proto3" json:"map_enum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=ComplexMessage_SimpleEnum"`
	MapScalar map[int32]int32                         `protobuf:"bytes,6,rep,name=map_scalar,json=mapScalar,proto3" json:"map_scalar,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	MapMsg    map[int32]*ComplexMessage_SimpleMessage `protobuf:"bytes,7,rep,name=map_msg,json=mapMsg,proto3" json:"map_msg,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Repeated
	REnum                []ComplexMessage_SimpleEnum     `protobuf:"varint,8,rep,packed,name=r_enum,json=rEnum,proto3,enum=ComplexMessage_SimpleEnum" json:"r_enum,omitempty"`
	RScalar              []int32                         `protobuf:"varint,9,rep,packed,name=r_scalar,json=rScalar,proto3" json:"r_scalar,omitempty"`
	RMsg                 []*ComplexMessage_SimpleMessage `protobuf:"bytes,10,rep,name=r_msg,json=rMsg,proto3" json:"r_msg,omitempty"`
	RBytes               [][]byte                        `protobuf:"bytes,11,rep,name=r_bytes,json=rBytes,proto3" json:"r_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ComplexMessage) Reset()         { *m = ComplexMessage{} }
func (m *ComplexMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage) ProtoMessage()    {}
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_full_275f2977295e095e, []int{0}
}
func (m *ComplexMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage.Unmarshal(m, b)
}
func (m *ComplexMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage.Marshal(b, m, deterministic)
}
func (dst *ComplexMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage.Merge(dst, src)
}
func (m *ComplexMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage.Size(m)
}
func (m *ComplexMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage proto.InternalMessageInfo

func (m *ComplexMessage) GetEnum() ComplexMessage_SimpleEnum {
	if m != nil {
		return m.Enum
	}
	return ComplexMessage_UNSPECIFIED
}

func (m *ComplexMessage) GetScalar() int32 {
	if m != nil {
		return m.Scalar
	}
	return 0
}

func (m *ComplexMessage) GetMessage() *ComplexMessage_SimpleMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ComplexMessage) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func (m *ComplexMessage) GetMapEnum() map[int32]ComplexMessage_SimpleEnum {
	if m != nil {
		return m.MapEnum
	}
	return nil
}

func (m *ComplexMessage) GetMapScalar() map[int32]int32 {
	if m != nil {
		return m.MapScalar
	}
	return nil
}

func (m *ComplexMessage) GetMapMsg() map[int32]*ComplexMessage_SimpleMessage {
	if m != nil {
		return m.MapMsg
	}
	return nil
}

func (m *ComplexMessage) GetREnum() []ComplexMessage_SimpleEnum {
	if m != nil {
		return m.REnum
	}
	return nil
}

func (m *ComplexMessage) GetRScalar() []int32 {
	if m != nil {
		return m.RScalar
	}
	return nil
}

func (m *ComplexMessage) GetRMsg() []*ComplexMessage_SimpleMessage {
	if m != nil {
		return m.RMsg
	}
	return nil
}

func (m *ComplexMessage) GetRBytes() [][]byte {
	if m != nil {
		return m.RBytes
	}
	return nil
}

type ComplexMessage_SimpleMessage struct {
	SomeField            int32    `protobuf:"varint,1,opt,name=some_field,json=someField,proto3" json:"some_field,omitempty"`
	SomeField2           string   `protobuf:"bytes,2,opt,name=some_field2,json=someField2,proto3" json:"some_field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplexMessage_SimpleMessage) Reset()         { *m = ComplexMessage_SimpleMessage{} }
func (m *ComplexMessage_SimpleMessage) String() string { return proto.CompactTextString(m) }
func (*ComplexMessage_SimpleMessage) ProtoMessage()    {}
func (*ComplexMessage_SimpleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_full_275f2977295e095e, []int{0, 0}
}
func (m *ComplexMessage_SimpleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Unmarshal(m, b)
}
func (m *ComplexMessage_SimpleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Marshal(b, m, deterministic)
}
func (dst *ComplexMessage_SimpleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexMessage_SimpleMessage.Merge(dst, src)
}
func (m *ComplexMessage_SimpleMessage) XXX_Size() int {
	return xxx_messageInfo_ComplexMessage_SimpleMessage.Size(m)
}
func (m *ComplexMessage_SimpleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexMessage_SimpleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexMessage_SimpleMessage proto.InternalMessageInfo

func (m *ComplexMessage_SimpleMessage) GetSomeField() int32 {
	if m != nil {
		return m.SomeField
	}
	return 0
}

func (m *ComplexMessage_SimpleMessage) GetSomeField2() string {
	if m != nil {
		return m.SomeField2
	}
	return ""
}

func init() {
	proto.RegisterType((*ComplexMessage)(nil), "ComplexMessage")
	proto.RegisterMapType((map[int32]ComplexMessage_SimpleEnum)(nil), "ComplexMessage.MapEnumEntry")
	proto.RegisterMapType((map[int32]*ComplexMessage_SimpleMessage)(nil), "ComplexMessage.MapMsgEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "ComplexMessage.MapScalarEntry")
	proto.RegisterType((*ComplexMessage_SimpleMessage)(nil), "ComplexMessage.SimpleMessage")
	proto.RegisterEnum("ComplexMessage_SimpleEnum", ComplexMessage_SimpleEnum_name, ComplexMessage_SimpleEnum_value)
}

func init() { proto.RegisterFile("full.proto", fileDescriptor_full_275f2977295e095e) }

var fileDescriptor_full_275f2977295e095e = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0x53, 0xc7, 0xc9, 0x49, 0x57, 0x2c, 0x6b, 0x82, 0x50, 0x18, 0x58, 0xbb, 0xca,
	0x55, 0xc5, 0xd2, 0x41, 0x27, 0x04, 0x17, 0xdb, 0xc8, 0xa4, 0x49, 0x14, 0x90, 0xab, 0x4d, 0xdc,
	0x45, 0x19, 0x78, 0xd5, 0x44, 0xdc, 0x56, 0x4e, 0x8b, 0xe8, 0x1b, 0xf1, 0x50, 0x3c, 0x00, 0x8f,
	0x81, 0xec, 0xa4, 0xab, 0x3b, 0x45, 0xea, 0x5d, 0x3e, 0x9f, 0xf3, 0xff, 0xfa, 0xf5, 0x1f, 0x05,
	0xe0, 0x76, 0x59, 0x14, 0xfd, 0xb9, 0x9a, 0x2d, 0x66, 0x87, 0x7f, 0x31, 0x74, 0xcf, 0x67, 0x72,
	0x5e, 0x88, 0xdf, 0x23, 0x51, 0x96, 0xf9, 0x44, 0xd0, 0x3e, 0xb4, 0xc5, 0x74, 0x29, 0x23, 0x87,
	0x39, 0x71, 0x37, 0xe9, 0xf5, 0xb7, 0xc7, 0xfd, 0xf1, 0x9d, 0xc6, 0x74, 0xba, 0x94, 0xdc, 0xec,
	0xd1, 0x27, 0xe0, 0x95, 0xdf, 0xf3, 0x22, 0x57, 0x51, 0x8b, 0x39, 0x31, 0xe2, 0x35, 0xd1, 0x21,
	0x60, 0x59, 0x69, 0x22, 0x97, 0x39, 0x71, 0x98, 0x1c, 0x34, 0x5b, 0xd5, 0xc4, 0xd7, 0xdb, 0x74,
	0x1f, 0xd0, 0xcd, 0x6a, 0x21, 0xca, 0xa8, 0xcd, 0x9c, 0xb8, 0xc3, 0x2b, 0xa0, 0x43, 0xf0, 0x65,
	0x3e, 0xcf, 0x4c, 0x34, 0xc4, 0xdc, 0x38, 0x4c, 0x5e, 0x3c, 0xf4, 0x1b, 0xe5, 0x73, 0x9d, 0x2b,
	0x9d, 0x2e, 0xd4, 0x8a, 0x63, 0x59, 0x11, 0xfd, 0x00, 0xa0, 0x85, 0x75, 0x46, 0xcf, 0x48, 0x5f,
	0x36, 0x48, 0xc7, 0x66, 0xa1, 0x12, 0x07, 0x72, 0xcd, 0xf4, 0x18, 0xb4, 0x53, 0x26, 0xcb, 0x49,
	0x84, 0x8d, 0xf6, 0x79, 0x83, 0x76, 0x54, 0x4e, 0x2a, 0xa1, 0x27, 0x0d, 0xd0, 0x23, 0xf0, 0x54,
	0x95, 0xd5, 0x67, 0xee, 0x8e, 0x1a, 0x91, 0x32, 0x39, 0x9f, 0x81, 0xaf, 0xd6, 0x29, 0x03, 0xe6,
	0xc6, 0x88, 0x63, 0x55, 0x67, 0x48, 0x00, 0x29, 0x93, 0x00, 0x4c, 0x82, 0x1d, 0x45, 0xb6, 0x95,
	0x4e, 0xf0, 0x14, 0xb0, 0xca, 0xaa, 0x1e, 0x43, 0xe6, 0xc6, 0x1d, 0xee, 0xa9, 0x33, 0x4d, 0xbd,
	0x2f, 0xb0, 0xb7, 0xb5, 0x4f, 0x0f, 0x00, 0xca, 0x99, 0x14, 0xd9, 0xed, 0x9d, 0x28, 0x7e, 0x98,
	0xb3, 0x23, 0x1e, 0xe8, 0x97, 0x0b, 0xfd, 0x40, 0x5f, 0x41, 0xb8, 0x19, 0x27, 0xe6, 0xc8, 0x01,
	0x87, 0xfb, 0x79, 0xd2, 0xbb, 0x86, 0x8e, 0xdd, 0x3c, 0x25, 0xe0, 0xfe, 0x14, 0xab, 0xda, 0x48,
	0x7f, 0xd2, 0xd7, 0x80, 0x7e, 0xe5, 0xc5, 0x52, 0x18, 0xf1, 0x8e, 0x32, 0xcc, 0xe2, 0xbb, 0xd6,
	0x89, 0xd3, 0x7b, 0x0f, 0xdd, 0xed, 0xb3, 0x34, 0x38, 0xef, 0xdb, 0xce, 0xc8, 0x56, 0x7f, 0x83,
	0xd0, 0x3a, 0x4c, 0x83, 0x74, 0x60, 0x4b, 0x77, 0x96, 0xba, 0x71, 0x3e, 0xfc, 0xe3, 0x00, 0x6c,
	0x12, 0xd3, 0xc7, 0x10, 0x5e, 0x7d, 0x1e, 0x7f, 0x4d, 0xcf, 0x2f, 0x2f, 0x2e, 0xd3, 0x8f, 0xe4,
	0x11, 0x0d, 0x01, 0x5f, 0x9f, 0x7e, 0xba, 0x4a, 0xb3, 0x53, 0xe2, 0x6c, 0xe0, 0x8c, 0xb4, 0x68,
	0x07, 0xfc, 0x1a, 0x8e, 0x88, 0x6b, 0x51, 0x42, 0xda, 0x16, 0x0d, 0x08, 0xb2, 0xe8, 0x98, 0x78,
	0x16, 0xbd, 0x21, 0xd8, 0xa2, 0xb7, 0xc4, 0xb7, 0x68, 0x48, 0x02, 0xba, 0x77, 0x4f, 0x27, 0xe4,
	0x1f, 0xbe, 0xf1, 0xcc, 0x5f, 0x3e, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x59, 0xe5, 0xea,
	0xf3, 0x03, 0x00, 0x00,
}
